spring:
  mongodb:
    embedded:
      version: 4.0.12
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    password: ''
  h2:
    console:
      enabled: true
      path: /database
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8081